name: pull

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - release/*
      - landchecks/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  linux-focal-rocm5_2-py3_7-build:
    # don't run build twice on master
    if: github.event_name == 'pull_request'
    name: linux-focal-rocm5.2-py3.7
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-focal-rocm5.2-py3.7
      docker-image-name: pytorch-linux-focal-rocm5.2-py3.7
      sync-tag: rocm-build
